### ISSUE TITLE
Redis clients not disconnecting

### ISSUE THREAD

**Issue by jvmiert** [singingwolfboy/flask-sse#6]
Hello David,

I'm using your Flask extension and it has been super helpful so thank you for making it available!

I've been running into an issue however and was hoping you could help out. For some reason Redis clients keep filling up. Whenever someone starts listening for events it never disconnects. Only after I restart the Gunicorn instance running your Flask SSE extension do the clients disappear.

I'm running Flask SSE as follows:
`gunicorn --workers 1 --worker-class gevent --bind unix:sse.sock -m 007 run_sse:app`

Versions:
```
gunicorn==19.7.0
Flask==0.12
gevent==1.1.1
Flask-SSE==0.2.1
redis==2.10.5
```

I run behind Nginx with the following configuration:
```
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_redirect off;
proxy_buffering off;
proxy_cache off;
proxy_read_timeout 24h;
proxy_pass http://sse_server;
chunked_transfer_encoding off;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```
And here is the Flask SSE code:
```python
from flask import Flask
from flask_sse import sse


app = Flask(__name__)
app.config["REDIS_URL"] = "redis://localhost"
app.register_blueprint(sse, url_prefix='/listen')
```
I'm running a separate synchronous Gunicorn worker where I render the webpages where the client side code is found. This separate Flask instance also publishes to Redis. I use your extension only to listen for events. Is this the reason that Redis is filling up?

Or am I doing something wrong in my Nginx configuration?

Hoping you can shed some light on the situation.

Thank you for you time.

**Comment by singingwolfboy** [comment]
I don't know the answer to your problem, unfortunately. I notice that you're only using one gunicorn worker, which seems strange -- have you tried increasing it? Have you tried isolating the problem, by removing one part of the try stack at a time until the problem goes away? The problem might be with gunicorn or nginx, rather than with Flask-SSE.

**Comment by jvmiert** [comment]
Thanks for your reply!

The number of workers didn't change anything. It seems that the flask request never ends. I'm not really experienced but when I try to setup a teardown_request, it never fires. So I guess somewhere it hangs and never ends the request even though the connection is closed on the client side? This would explain Redis connections piling up.

**Comment by jvmiert** [comment]
So I think I figured out that the Flask process doesn't know the client is disconnected. Only after it tries to send something again it will realize that there is no longer a client on the other side and fails silently. 

The following code catches this:
```python
@stream_with_context
def generator():
    try:
        for message in self.messages(channel=channel):
            yield str(message)
    except:
        current_app.logger.debug('client disconnected')
````

I tried to disconnect Redis during this moment by doing this:

```python
self.redis.connection_pool.disconnect()
```

Sadly this doesn't work. I'm not sure how to proceed from here. I will dive a little more into this when I have time and share what I find.

**Comment by bmjjr** [comment]
I'm running into hitting SQLAlchemy connection pool limits which I suspect is related to this. I'm on similar versions as @piloe but without gunicorn, using a gevent-server script. 

The issue is for any value of my SQLALCHEMY_POOL_SIZE setting, for every page refresh or just navigating throughout the app, a connection from the pool is consumed but not released, and I eventually hit a limit and error out. If I set debug=False, then it doesn't help, I still end up hitting a limit and get a "server error" message. 

Could it be the way StrictRedis is called, it should be called with an explicit connection pool option?  There is another earlier Flask-SSE repo that is similar but not quite the same as thus one, and that repo uses a ConnectionPool class with `return StrictRedis(connection_pool=pool)`.  https://github.com/DazWorrall/flask-sse/blob/master/flask_sse.py

**Comment by bmjjr** [comment]
On further review, I don't think this is relevant to my connection pool limit issue mentioned above.

**Comment by tamarmot** [comment]
We are having the exact same issues as @piloe, where the flask is making and holding a connection to redis even after the tcp connection on the other side disconnects.  Any updates on this?

**Comment by singingwolfboy** [comment]
@tamarmot No updates on this, unfortunately. I don't actually use this code in production, so I can't help very much.

**Comment by tamarmot** [comment]
Ok thanks @singingwolfboy we will be playing around with it ... we are using it heavily and have 1179 open connections to redis at the moment and still growing ...

**Comment by bmjjr** [comment]
@tamarmot I implemented connection pooling as per below, seems to work well but I haven't used it under heavy load yet:
```
# -*- coding: utf-8 -*-
"""for sse in other blueprints, import this blueprint as sse"""

from flask import current_app, stream_with_context
from flask_sse import ServerSentEventsBlueprint
import redis
from base.settings import Config

class RedisWrapper:
    """
    https://stackoverflow.com/a/31807468/1493069
    """
    shared_state = {}
    def __init__(self):
        """create the redis wrapper object"""
        self.__dict__ = self.shared_state

    def redis_connect(self, server_key):
        redis_server_conf = Config.REDIS_SERVER_CONF['servers'][server_key]
        connection_pool = redis.ConnectionPool(host=redis_server_conf['HOST'],
                                               port=redis_server_conf['PORT'],
                                               db=redis_server_conf['DATABASE'])
        return redis.StrictRedis(connection_pool=connection_pool)


class PooledSSEBP(ServerSentEventsBlueprint):
    """
    ISSUES:
    https://github.com/singingwolfboy/flask-sse/issues/6

    Connection Pool References:
        https://github.com/niwinz/sse/blob/master/sse.py
        https://github.com/DazWorrall/flask-sse/blob/master/flask_sse.py
    """

    @property
    def redis(self):
        """
        A :class:`redis.StrictRedis` instance, configured to connect to the
        current application's Redis server.
        """
        redis_conf = current_app.config.get("REDIS_SERVER_CONF")
        if not redis_conf:
            raise KeyError("Must set a REDIS_SERVER_CONF in app config.")
        return RedisWrapper().redis_connect(server_key='main_server')

    def stream(self, **kwargs):
        """
        A view function that streams server-sent events. Ignores any
        :mailheader:`Last-Event-ID` headers in the HTTP request.
        Use a "channel" query parameter to stream events from a different
        channel than the default channel (which is "sse"). This is
        overridden to add **kwargs to accomidate the host_matching for
        host='<string:subdom>.local:8000' in the blueprint.
        """
        channel = request.args.get('channel') or 'sse'

        @stream_with_context
        def generator():
            for message in self.messages(channel=channel):
                yield str(message)

        return current_app.response_class(
            generator(),
            mimetype='text/event-stream',
        )

# override the flask_sse bluerint
blueprint = PooledSSEBP('sse', __name__,
                        url_prefix='/app/sse',
                        template_folder='templates',
                        static_folder="../static")

sse = blueprint  # this is just sugar
# access stream at url_for('sse.stream', channel=<channel>)
blueprint.add_url_rule(rule="/", endpoint="stream", view_func=sse.stream,
                       host='<string:subdom>.local:8000')

# import at the bottom to avoid problems!
from .sse_view import *
```

**Comment by tamarmot** [comment]
Thanks, we did our own implementation of that and tested it yesterday but it did not fix the problem.  Unfortunately we're going to have to try some different technology.  I'm still baffled as to why this system is not properly letting go of the redis connections.

**Comment by jvmiert** [comment]
I sadly haven't figured this out either. I think the reason this is happening is because of the nature of SSE it is hard to know when a client disconnects. Right now when an event needs to send it will fail if the client is disconnected on the other side. For some reason when this fail happens Flask doesn't shutdown and clean up properly and the connection to Redis is left open. I haven't been able to fix this.

We are also switching to other technology. In the mean time we have the luxury of being able to restart the process daily and thus freeing connections.

**Comment by singingwolfboy** [comment]
Since there's been no activity on this issue in years, I'm closing it.
